### ISSUE TITLE
Publish @next to NPM

### ISSUE THREAD

**Issue by thegecko** [eclipse-cdt/cdt-gdb-adapter#133]
I'd like to see the CI/build system automatically publish and tag each master commit to npm.

This would allow any PR to be got from npm and to have the latest master version always available (with the addition of an `next`) tag.

In theory it should be as simple as adding the following to the CI:

```
npm --no-git-tag-version version prerelease --preid=next.$(echo $COMMITID | cut -c -7)
npm publish --tag next
```

I'd be happy to do this, but can't see how the CI system is setup and integrated.

An example for CircleCI can be seen here:

https://github.com/thegecko/webusb/blob/master/circle.yml#L27

**Comment by jonahgraham** [comment]
Fully in support. I will kick the ball off on this once I complete the CDT 9.9 release work I need to do.

**Comment by thegecko** [comment]
Any progress @jonahgraham ?

**Comment by jonahgraham** [comment]
Not yet, I am just [today finishing](https://www.eclipse.org/lists/cdt-dev/msg33755.html) off CDT 9.9 release work, so will be at this soon.

**Comment by jonahgraham** [comment]
The commands I will use are:

```
yarn version  --no-git-tag-version --prerelease --preid=next.$(git rev-parse --short HEAD)
yarn publish --non-interactive --tag next
```

This needs to be run in an environment that has already been logged in to npmjs (e.g. by using npm login).

To do this on CI we need a CDT bot user. I have [requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551543) this from webmaster at which time I will automate it in the [Jenkinsfile](https://github.com/eclipse-cdt/cdt-infra/blob/master/jenkins/pipelines/cdt/npm-builds/cdt-gdb-adapter-master.Jenkinsfile#L22). 

---

While we wait I will manually publish every master commit and have done that for https://github.com/eclipse-cdt/cdt-gdb-adapter/commit/478303332c5d1385e301b71e437a68f1c8551825 --> [cdt-gdb-adapter@next](https://www.npmjs.com/package/cdt-gdb-adapter/v/0.0.14-next.4783033.0)

**Comment by thegecko** [comment]
Hi @jonahgraham, is this still in progress?

Would you mind releasing the latest master so recent changes can be consumed?

**Comment by jonahgraham** [comment]
Hi @thegecko - sorry I forgot to manually publish after merging your changes. I have [pinged ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551543#c1) webmaster so that we can proceed with the automation.

**Comment by jonahgraham** [comment]
Done. https://www.npmjs.com/package/cdt-gdb-adapter/v/0.0.14-next.8084f52.0

**Comment by jonahgraham** [comment]
@thegecko I have tried to get this to work on CI - so far no luck. If you have any thoughts I would appreciate it on: [Bug 551543 Comment 4](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551543#c4)

**Comment by thegecko** [comment]
Has the bot been added to npm as an admin of this package?

**Comment by thegecko** [comment]
Then it should be a matter of just writing the token to the .npmrc each time (see my example above). Are the commands visible somewhere?

**Comment by jonahgraham** [comment]
The jenkinsfile is https://github.com/eclipse-cdt/cdt-infra/blob/master/jenkins/pipelines/releng/npm-token-test.Jenkinsfile -- Bug 551543 Comment 4 has the links to the outputs showing npm whoami getting a 401.

**Comment by thegecko** [comment]
Hmm, the npm owner list only shoews one user:

```
> npm owner ls
> cdtdoug <cdtdoug@gmail.com>
```

Is that the bot?

Can you publish using the bot credentials outside of jenkins?

**Comment by jonahgraham** [comment]
The bot is not an account I have access to. My issue is not publishing, it is earlier in the process, I can't even do npm whoami.

**Comment by thegecko** [comment]
npm whoami won't work unless npm recognises the bot account as an npm user

**Comment by jonahgraham** [comment]
Thanks @thegecko - did you have a look at Bug 551543? Do you see something happening there that is wrong? If so please comment there.

**Comment by thegecko** [comment]
From what I can see it all looks fine. I cant see what the bot name is, but we need to confirm its been added as a user to the npm repo before it will work.

**Comment by jonahgraham** [comment]
It has been added in the same way as I have and I can push releases no problem.

**Comment by jonahgraham** [comment]
c89a648 published to [npmjs](https://www.npmjs.com/package/cdt-gdb-adapter/v/0.0.14-next.c89a648.0) - hopefully we can get this automatic publishing unlocked soon

**Comment by jonahgraham** [comment]
It is all working automatically now: [CI job](https://ci.eclipse.org/cdt/view/npm%20builds/job/cdt-gdb-adapter-master/82/console) - commit 921da89 auto-published to [npmjs](https://www.npmjs.com/package/cdt-gdb-adapter/v/0.0.14-next.921da89.0)

**Comment by thegecko** [comment]
woot!

**Comment by jonahgraham** [comment]
While we are publishing - the versioning scheme isn't good as the git sha1 in the version number means that older versions are considered upgrades on newer ones.

e.g: Today's `@next` is 0.0.14-next.921da89.0 - but doing `yarn upgrade` "upgrades" to 0.0.14-next.c89a648.0 because it has a "bigger" version number.

So we need a better versioning system than this.

**Comment by jonahgraham** [comment]
How about `next.$(date -u "+%Y%m%d%H%M%S").$(git rev-parse --short HEAD)` for preid? Makes it long, but sorts properly. I don't think we'll fix 0.0.14 as I will release that version to match what is being shipped in CDT plug-ins release. (In the future when cdt-vscode plug-ins are released I think we'll do the same thing).

**Comment by thegecko** [comment]
> the git sha1 in the version number means that older versions are considered upgrades on newer ones

I think you are perceiving an issue which doesn't exist.
I'll explain, but apologies if any of this sounds patronising :)

The normal way npm packages are published is as a manual step to run `npm publish`. This publishes the package using the version in `package.json`. In our case the last one to be released was `0.0.13`.

Unless a tag is specified, npm automatically tags that release as `@latest` (see https://docs.npmjs.com/cli/publish), e.g.:

0.0.13 <- latest
0.0.12
0.0.11

When the next publish is done, the latest tag is automatically updated:

0.0.14 <- latest
0.0.13
0.0.12
0.0.11

When a user installs the package (e.g. `npm i cdt-gdb-adapter`) they are given the version that `@latest` points at by default.
When they upgrade, their current version is checked against any new version with the `@latest` tag, ignoring all other versions.
Versioning honours the [semver](https://docs.npmjs.com/about-semantic-versioning) system.

Importantly, this is how all production or stable versions are managed on npm.

Onto the automatic stuff...

Many package owners also like to publish the (less stable) bleeding edge versions without making them the latest. This allows users to take the latest codebase at their own risk without forcing these versions onto all users.
There are many ways this is done, but a common idiom is to publish all master releases, but instead of using the `@latest` tag, the `@next` tag is used (which doesn't have any special properties like latest).

e.g.:

974a28 <- next
324abc
0.0.13 <- latest
94d34b
0.0.12
0.0.11

and then:

0.0.14 <- latest
974a28 <- next
324abc
0.0.13
94d34b
0.0.12
0.0.11

You can see this in our own [cdt-gdb-adapter version history](https://www.npmjs.com/package/cdt-gdb-adapter?activeTab=versions)

This means users can install a specific master commit or track `@next` to always have the latest master.
IMO, users using these releases are only doing it as a stop-gap to pick up bug-fixes between stable releases and shouldn't be upgrading them (hence the sha1 version issue described shouldn't matter).

Also, by changing the version used for our `@next` releases, it will be harder to map a release to a commit hash.

My only recommendation is that we manually release stable versions more often using the [semver guidelines](https://docs.npmjs.com/about-semantic-versioning). The current latest release is really out of date :)

I've also noticed our [package.json version](https://github.com/eclipse-cdt/cdt-gdb-adapter/blob/master/package.json#L3) explicitly has `-next` in it. This isn't needed as it's a tag added during the automatic publish.

**Comment by jonahgraham** [comment]
> stop-gap to pick up bug-fixes between stable releases and shouldn't be upgrading them

This is the part that I don't get - I have other pre-release projects that depend on pre-release cdt-gdb-adapter. I was treating the @next like -SNAPSHOT in maven land. In the dependent projects I (want to) do `yarn upgrade` to get the most recent snapshot and do the builds. Instead I can do `yarn add cdt-gdb-adapter@next` -- but then I still have to remember that `yarn upgrade` breaks stuff :-(

>  or track @next

This may simply be what I am missing - what is the correct way to track `@next`?

> Also, by changing the version used for our @next releases, it will be harder to map a release to a commit hash.

My proposal is 0.0.14-next.$DATE.$SHA1.0: https://github.com/eclipse-cdt/cdt-gdb-adapter/issues/133#issuecomment-562882883

**Comment by thegecko** [comment]
`yarn upgrade` shouldn't break stuff, it should only look at the `@latest` tag (which is quite out of date)

**Comment by jonahgraham** [comment]
I assume you haven't had a chance to test it - doing a yarn upgrade is how I found the problem - it turned out the one it upgraded to was the one that had the cross-spawn dep missing in it.

```
$ yarn init 
yarn init v1.19.1
question name (x): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
Done in 2.12s.

$ yarn add cdt-gdb-adapter@next
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
info Direct dependencies
└─ cdt-gdb-adapter@0.0.14-next.921da89.0
info All dependencies
├─ cdt-gdb-adapter@0.0.14-next.921da89.0
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ node-addon-api@1.7.1
├─ vscode-debugadapter@1.37.1
└─ vscode-debugprotocol@1.37.0
Done in 2.83s.

$ yarn upgrade
yarn upgrade v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
error /tmp/x/node_modules/cdt-gdb-adapter: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /tmp/x/node_modules/cdt-gdb-adapter
Output:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/x/node_modules/cdt-gdb-adapter/install.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

**Comment by thegecko** [comment]
Very interesting, this is certainly challenging how I thought it worked. Out of interest, I wonder if a yarn upgrade from the official release (0.0.13) does the same?

**Comment by thegecko** [comment]
Anyway, I'm certainly not wed to the existing @next format, so feel free to change it if you like.

**Comment by jonahgraham** [comment]
0.0.14 is now published - official release is on 18 Dec for Eclipse legal purposes.

And 0.0.15@next are tagged with date-sha1:
https://github.com/eclipse-cdt/cdt-infra/commit/e1bd543e265fef5137df4da76c64bdc04b2bb92b
