### ISSUE TITLE
Future plans for cdt-gdb-adapter

### ISSUE THREAD

**Issue by danieltomasku** [eclipse-cdt/cdt-gdb-adapter#166]
Hi there!

First off, thank you for creating this nice adapter 😃

I was wondering what the plans are for the cdt-gdb-adapter and whether it will continue to be actively maintained. My team is working on a project that uses the cdt-gdb-adapter, however, I wanted to make sure that we are placing a safe bet on the future of this adapter before we go much further.  Any insights into the plans of the cdt-gdb-adapter would be much appreciated! 
Thank you.

**Comment by jonahgraham** [comment]
Hi @danieltomasku - I am glad you have found the adapter and are considering it.

The adapter will continue to be maintained. Amongst others, mbed studio (which just had its [1.0 release](https://os.mbed.com/blog/entry/mbed-studio-1-release/)) are using it. cdt-gdb-adapter is one of the building blocks for the [Theia CPP extension](https://github.com/eclipse-theia/theia-cpp-extensions/) and Eclipse Theia is certainly a growing area these days.

Numerous companies are actively investigating the future of C/C++ IDEs and the cdt-gdb-adapter is a key building block for that.

Please let me know if there is more I can do to help.

Jonah

**Comment by jonahgraham** [comment]
@danieltomasku I noticed on your GitHub profile you are at Ericsson - As Ericsson in Montreal is one of the biggest contributors to this adapter, you may find some good information internal to your company. @marechal-p Perhaps you can comment?

**Comment by danieltomasku** [comment]
Thank you for the response @jonahgraham. The repo had been a little quiet lately and I just wanted to make sure there weren't any plans to deprecate it, but sounds like that is not the case! 😄  I have been in touch with @marechal-p and will ask him more questions. Thanks again!

**Comment by jonahgraham** [comment]
Great @danieltomasku  - I hope you can find good use out of the adapter. I look forward to any fixes and/or bug reports you have.
