### ISSUE TITLE
Improve C++ support in Variables view

### ISSUE THREAD

**Issue by jcrwilliams** [eclipse-cdt/cdt-gdb-adapter#25]
Investigate and address any deficiencies relating to how variables are displayed and set.  Have not yet done any testing/experimentation with how C++ programs behave in this view so this is a blanket issue for any findings that occur.

**Comment by jcrwilliams** [comment]
As it stands, we do not display variables in C++ objects properly, as they exist under a valueless, typeless child elements reflecting their public/protected/private status. I will be adding support for this in an upcoming patch.

Interestingly, my investigation shows that the Eclipse CDT debug scenario chokes on C code that uses public/protected/private as a variable name inside of a structure. eg)
```
struct foo {
    int public;
};
```

**Comment by simark** [comment]
> Interestingly, my investigation shows that the Eclipse CDT debug scenario chokes on C code that uses public/protected/private as a variable name inside of a structure. eg)
> 
> ```
> struct foo {
>     int public;
> };
> ```

Ha, nice test case :)
