### ISSUE TITLE
Running tests after a force push

### ISSUE THREAD

**Issue by simark** [eclipse-cdt/cdt-gdb-adapter#35]
I uploaded a PR (#34) and noticed I had a typo.  I fixed it and force-pushed my branch.  The Jenkins tests ran initially, but did not run after the force push.  Is it expected?

**Comment by simark** [comment]
Ahhh nevermind, it ran 5 minutes after, I just need to be a bit more patient.

**Comment by jonahgraham** [comment]
> Ahhh nevermind, it ran 5 minutes after, I just need to be a bit more patient.

@simark Unfortunately we can't have hooks on github to Eclipse Jenkins, so the Jenkins plug-in polls github instead every 5 minutes. It is a noticeably long time some times!

**Comment by dschaefer** [comment]
Yeah, has caught me a few times too. We could bump it up faster, but let's see how mad we get at it first ;).

**Comment by simark** [comment]
> Yeah, has caught me a few times too. We could bump it up faster, but let's see how mad we get at it first ;).

It's fine like this, once you know it :).
