### ISSUE TITLE
Dirty package-lock.json when rebuilding

### ISSUE THREAD

**Issue by simark** [eclipse-cdt/cdt-gdb-adapter#49]
When I rebuild the project, I often get some changes in package-lock.json.  It is often `"optional": true`, added to many packages.  Anybody knows why this happens?  Is this an npm version issue?

**Comment by dschaefer** [comment]
I see that occasionally too. Not sure why. In the end, I just make sure I'm using the latest npm.

Almost enough to make me want to head back to yarn. Though we had issues with timeouts on the build machine with yarn. Sigh...

**Comment by dschaefer** [comment]
BTW, is this an example of a topic that would be easier to discuss in a forum like Gitter or Mattermost or whatever? Or is raising issues like this OK? Still trying to figure that all out.

**Comment by simark** [comment]
For traceability, I think issues are good, but still it would be nice to have a chat.  We already use gitter for Theia, so I don't mind if it's there, but if it makes more sense to use Eclipse's Mattermost, that's fine with me too.  I would actually prefer IRC, but I'm sure it won't fly very high here :).

**Comment by simark** [comment]
> I see that occasionally too. Not sure why. In the end, I just make sure I'm using the latest npm.
> 
> Almost enough to make me want to head back to yarn. Though we had issues with timeouts on the build machine with yarn. Sigh...

Even with the same node version, running it multiple times in a row gives different results (though it eventually converges)...

**Comment by dschaefer** [comment]
Might be worth trying out yarn again. I'll play with that if I get a chance today. Again biggest issue was timeouts on ci.eclipse.org. Yarn seems to get the packages through it's own proxy.

**Comment by simark** [comment]
> Might be worth trying out yarn again. I'll play with that if I get a chance today. Again biggest issue was timeouts on ci.eclipse.org. Yarn seems to get the packages through it's own proxy.

I don't mind.  I have the impression that projects keep switching between yarn and npm, choosing which one has less severe issues at the moment :).

**Comment by dschaefer** [comment]
> For traceability, I think issues are good, but still it would be nice to have a chat. We already use gitter for Theia, so I don't mind if it's there, but if it makes more sense to use Eclipse's Mattermost, that's fine with me too. I would actually prefer IRC, but I'm sure it won't fly very high here :).

BTW, opened a bug to discuss this. https://bugs.eclipse.org/bugs/show_bug.cgi?id=542679

**Comment by dschaefer** [comment]
Switching to yarn. Should hopefully fix this.

**Comment by simark** [comment]
I'll close it, since it was more a question than a problem report.
