### ISSUE TITLE
Reuse VSCode GDB adapter?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-cdt/cdt-gdb-adapter#56]
I see the VSCode extension for C++ has support for GDB: https://github.com/Microsoft/vscode-cpptools/search?q=gdb&unscoped_q=gdb . It seems that just invoking the right `.js` file with the right arguments and passing the right `launch.json` initialization message would enable debugging with GDB.
Have you tried it? What is the expected added value of this debug adapter over the one used in VSCode?

**Comment by mickaelistria** [comment]
See also https://www.youtube.com/watch?v=aWIs6Kv1MvE

**Comment by mickaelistria** [comment]
About license, the VSCode extension is MIT.
It starts the adapter by calling command `extension.cppdbgAdapterExecutableCommand` https://github.com/Microsoft/vscode-cpptools/blob/35288aad1778e4b7468d752a7a58e2b2e225efdf/Extension/package.json#L537
This `extension.cppdbgAdapterExecutableCommand` is implemented at https://github.com/Microsoft/vscode-cpptools/blob/35288aad1778e4b7468d752a7a58e2b2e225efdf/Extension/src/Debugger/extension.ts#L58 and starts the wraps OpenDebugAD7 which is MIT https://github.com/Microsoft/MIEngine/tree/master/src/OpenDebugAD7 in a VSCode Debug Adapter.
It seems to me that this is already a good MI<->DAP conversion API available.

**Comment by mickaelistria** [comment]
With a basic `ps` while VSCode debugger is running, the right command line to start the debug adapter might just popup.

**Comment by dschaefer** [comment]
Does the VSCode debug adapter support the extensions we need to reach parity with the Eclipse CDT plugins like memory browsing and viewing registers?

**Comment by mickaelistria** [comment]
I don't know and that's beyond my knowledge of GDB and CDT to be able to provide an answer. I still think it should be audited as VSCode Debug Adapter is more mature and already has a lot of features implemented. If it's good and is open (technically and "politically") for such additions, it seems more profitable to place effort there and have CDT reusing it.

**Comment by dschaefer** [comment]
We have had a quick look at it. Not excited that it's written in C# since we don't know C#. We already have a start on memory browsing which, if Microsoft's doesn't have, puts ours ahead of theirs in functionality.

BTW, my eyes are more on PlatformIO's IDE. It is pretty close to feature parity with CDT than what I've seen with Microsofts. https://platformio.org/platformio-ide

At any rate, this adapter is part of a bigger strategy of producing a VS Code C/C++ extension equivalent to our Eclipse plug-ins, done in such a way we can reuse components between VS Code (and Theia) and Eclipse. As such, feature parity with our existing Eclipse plug-ins is our primary requirement.

And, we are open for contributions and would be happy if Microsoft and the PlatformIO guys would join us.

**Comment by jonahgraham** [comment]
> About license, the VSCode extension is MIT.

We had a look at this too, there are two licenses published for this. The one in the [repo](https://github.com/Microsoft/vscode-cpptools/blob/master/LICENSE.txt) and the one on the [marketplace](https://marketplace.visualstudio.com/items/ms-vscode.cpptools/license). The marketplace contains this restriction:

> INSTALLATION AND USE RIGHTS. You may only use the C/C++ Extension for Visual Studio Code with Visual Studio Code, Visual Studio or Xamarin Studio software to help you develop and test your applications.

Also, IIRC the core of the adapter is not actually open source, only the wiring to connect the proprietary code to VS code is FOSS. The adapter core is in a debugAdapters directory that is not in the github repo (it contains the compiled .NET stuff).

**Comment by dschaefer** [comment]
Thanks Jonah. Let's consider this a non starter. Closing.

**Comment by mickaelistria** [comment]
Ok, thanks.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by mickaelistria** [comment]
Actuallu, it could be a good question foe legal:since we bund to code and
code says MIT, does the restrictive clause apply to this use-case?

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>
