### ISSUE TITLE
Need way to interrupt gdb

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt/cdt-gdb-adapter#62]
I'm looking at exit scenarios. If the inferior is busy running, we need a way to interrupt gdb so we can kill the inferior and gdb-exit. In CDT, we do this by sending the gdb process an interrupt signal (on *nix anyway, big kludge on Windows). Need to replicate that here.

**Comment by simark** [comment]
I think we need to be able to interrupt also just when the user wants to pause the program.

If we use GDB's `mi-async on` mode (#28), this is done using `-exec-interrupt`.  If we are in `mi-async off` (in particular, I don't think `mi-async on` is supported on Windows), GDB is not listening on the MI channel when the program is running, so we have to resort to sending a signal.

**Comment by dschaefer** [comment]
Cool, didn't know about mi-async. I'll give it a try. And yeah, Windows is going to be tricky either way.

**Comment by dschaefer** [comment]
Yup that worked great on Linux.

**Comment by simark** [comment]
The reason `mi-async on` is not supported by GDB on Windows is that the Windows target has not been ported to internally be asynchronous.  So when GDB resumes the debugged program, GDB stays blocked deep inside the Windows-specific code, waiting for an event (e.g. a stop) from the debugged program.  Meanwhile, it can't listen to events on other sources, such as the MI channel.  Initially all targets were like that, until they were modified to be all asynchronous.  The Windows target needs to be changed the same way.  There's no technical reason preventing this, it's just that nobody did it yet.

**Comment by dschaefer** [comment]
Our gdb for remote QNX targets also doesn't work. Good news is that we're part of CDT here and can grab the code and translate it for the adapter.

**Comment by simark** [comment]
> Our gdb for remote QNX targets also doesn't work.

Does work asynchronously you mean?  Some opportunities for improvement :)

**Comment by dschaefer** [comment]
> > Our gdb for remote QNX targets also doesn't work.
> 
> Does work asynchronously you mean? Some opportunities for improvement :)

:), yeah, it's pretty old code. We have our own 'target qnx' which I guess also isn't async.

**Comment by dschaefer** [comment]
The good news may be that node's process.kill support has emulation on Windows. We'll have to see if it works with gdb.

**Comment by dschaefer** [comment]
#96 gets us working on recent LInuxae and Mac with lldb-mi. We'll create bugs for Windows and older gdbs.
