### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by simark** [eclipse-cdt/cdt-gdb-adapter#9]
I am a big fan of lint tools, and I am sure you are too :).  tslint works really well.  I suggest to define rules early, so we don't have to do too many mechanical changes when the code base has grown.  I would suggest starting with `tslint:recommended` (see [here](https://palantir.github.io/tslint/usage/configuration/#configuration-presets)), and disabling rules that we find more annoying than useful.

**Comment by dschaefer** [comment]
Linting is good. We use VS Code and the TSLint extension with all out stuff. I just forgot to copy over our tslint.json file when I set this up. I can finish that and we can tweak it after.

**Comment by dschaefer** [comment]
Addressed in #10
